# fly.toml app configuration file generated for lms-backend-demo on 2025-12-10T16:46:15+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lms-backend-demo'
primary_region = 'bom'

[build]
  dockerfile = 'Dockerfile.fly'

[env]
  DATABASE_HOST = 'localhost'
  DATABASE_PORT = '5432'
  DATABASE_TYPE = 'postgres'
  NODE_ENV = 'production'
  REDIS_ENABLED = 'false'

[[mounts]]
  source = 'postgres_data'
  destination = '/var/lib/postgresql/data'

[[services]]
  protocol = 'tcp'
  internal_port = 3000
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = '30s'
    timeout = '3s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/v1'
    protocol = 'http'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
